In [0]:
from pyspark.sql import SparkSession

In [0]:
spark = SparkSession.builder.master('localhost[*]').appName('Superstore').getOrCreate()

In [0]:
spark

In [0]:
sc = spark.sparkContext
sc

In [0]:
import pandas as pd

In [0]:
data = spark.read.table('sample___eu_superstore_12_csv')
data.show()  #sample_eu_superstore_9_csv
# SHOW is a lazy operation.

+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-------------+--------------------+--------------+-------+---------------+---------------+------------+--------------------+--------+--------+--------+-------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID|   Customer Name|    Segment|         City|               State|       Country| Region|     Product ID|       Category|Sub-Category|        Product Name|   Sales|Quantity|Discount| Profit|
+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-------------+--------------------+--------------+-------+---------------+---------------+------------+--------------------+--------+--------+--------+-------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-ST-10000988|Office Supplies|     Storage|Fellowes Folders,...|    79.2|       3|     0.0|   39.6|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|TEC-AC-10004144|     Technology| Accessories|SanDisk Numeric K...|  388.92|       7|     0.0|    0.0|
|     3|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-LA-10001915|Office Supplies|      Labels|Avery Legal Exhib...|   35.19|       3|     0.0|  16.11|
|     4|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-ST-10004550|Office Supplies|     Storage|Fellowes Folders,...|   50.94|       2|     0.0|   13.2|
|     5|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|TEC-AC-10004068|     Technology| Accessories|Memorex Memory Ca...|  307.44|       3|     0.0|  73.71|
|     6|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-ST-10002271|Office Supplies|     Storage|Rogers Shelving, ...|   122.4|       2|     0.0|  37.92|
|     7|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|TEC-PH-10003963|     Technology|      Phones|Apple Signal Boos...|  413.82|       3|     0.0|  20.61|
|     8|ES-2016-5113958|02/08/2016|07/08/2016|  Second Class|   EB-13840|   Ellis Ballard|  Corporate|West Bromwich|             England|United Kingdom|  North|TEC-CO-10004325|     Technology|     Copiers|Canon Personal Co...|  428.22|       3|     0.0| 192.69|
|     9|ES-2016-5113958|02/08/2016|07/08/2016|  Second Class|   EB-13840|   Ellis Ballard|  Corporate|West Bromwich|             England|United Kingdom|  North|OFF-AP-10004512|Office Supplies|  Appliances|   Hoover Stove, Red| 3979.29|       7|     0.0|1989.54|
|    10|ES-2016-5113958|02/08/2016|07/08/2016|  Second Class|   EB-13840|   Ellis Ballard|  Corporate|West Bromwich|             England|United Kingdom|  North|OFF-FA-10002393|Office Supplies|   Fasteners|Accos Push Pins, ...|   43.56|       3|     0.0|   12.6|
|    11|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-LA-10002805|Office Supplies|      Labels|Hon Color Coded L...|   25.26|       2|     0.0|   0.48|
|    12|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-AP-10002330|Office Supplies|  Appliances|Hamilton Beach St...|2443.905|       5|     0.1|760.305|
|    13|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-AR-10000505|Office Supplies|         Art|Binney & Smith Pe...|   12.21|       1|     0.0|    0.0|
|    14|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|TEC-PH-10002898|     Technology|      Phones|Samsung Smart Pho...|2167.296|       4|    0.15|790.416|
|    15|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-ST-10001413|Office Supplies|     Storage|Rogers Folders, Blue| 138.105|       5|     0.1|-12.345|
|    16|ES-2017-4380115|16/02/2017|20/02/2017|Standard Class|   KC-16540| Kelly Collister|   Consumer|   Strasbourg|Alsace-Champagne-...|        France|Central|OFF-ST-10003931|Office Supplies|     Storage|Smead Trays, Wire...| 128.385|       3|     0.1|  4.275|
|    17|ES-2017-4380115|16/02/2017|20/02/2017|Standard Class|   KC-16540| Kelly Collister|   Consumer|   Strasbourg|Alsace-Champagne-...|        France|Central|TEC-AC-10004269|     Technology| Accessories|Belkin Memory Car...|  690.12|       6|     0.0|    0.0|
|    18|ES-2017-4380115|16/02/2017|20/02/2017|Standard Class|   KC-16540| Kelly Collister|   Consumer|   Strasbourg|Alsace-Champagne-...|        France|Central|OFF-LA-10001676|Office Supplies|      Labels|Hon Removable Lab...|    8.16|       1|     0.0|   1.14|
|    19|ES-2018-2573330|03/11/2018|08/11/2018|Standard Class|   BF-11170|      Ben Ferrer|Home Office|         Unna|North Rhine-Westp...|       Germany|Central|TEC-MA-10000811|     Technology|    Machines|Okidata Phone, Du...|  347.88|       4|     0.0|  76.44|
|    20|ES-2018-2573330|03/11/2018|08/11/2018|Standard Class|   BF-11170|      Ben Ferrer|Home Office|         Unna|North Rhine-Westp...|       Germany|Central|OFF-ST-10000648|Office Supplies|     Storage|Eldon File Cart, ...| 575.505|       5|     0.1| 12.705|
+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-------------+--------------------+--------------+-------+---------------+---------------+------------+--------------------+--------+--------+--------+-------+
only showing top 20 rows

In [0]:
df = sc.parallelize(['Lamee', 26, 1.8, 'Aisha'])
df

Out[2]: ParallelCollectionRDD[429] at readRDDFromInputStream at PythonRDD.scala:435

In [0]:
df.count()

Out[17]: 4

In [0]:
df.take(3)

Out[18]: ['Lamee', 26, 1.8]

In [0]:
df_collect = df.collect()

In [0]:
type(df_collect)

Out[20]: list

In [0]:
df_collect[:3]

Out[21]: ['Lamee', 26, 1.8]

In [0]:
data.printSchema()

root
 |-- Row ID: string (nullable = true)
 |-- Order ID: string (nullable = true)
 |-- Order Date: string (nullable = true)
 |-- Ship Date: string (nullable = true)
 |-- Ship Mode: string (nullable = true)
 |-- Customer ID: string (nullable = true)
 |-- Customer Name: string (nullable = true)
 |-- Segment: string (nullable = true)
 |-- City: string (nullable = true)
 |-- State: string (nullable = true)
 |-- Country: string (nullable = true)
 |-- Region: string (nullable = true)
 |-- Product ID: string (nullable = true)
 |-- Category: string (nullable = true)
 |-- Sub-Category: string (nullable = true)
 |-- Product Name: string (nullable = true)
 |-- Sales: double (nullable = true)
 |-- Quantity: integer (nullable = true)
 |-- Discount: double (nullable = true)
 |-- Profit: double (nullable = true)

In [0]:
type(data)

Out[23]: pyspark.sql.dataframe.DataFrame

In [0]:
data.columns

Out[24]: ['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'City',
 'State',
 'Country',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit']

In [0]:
data.count()

Out[25]: 10000

In [0]:
data

Out[4]: DataFrame[Row ID: string, Order ID: string, Order Date: string, Ship Date: string, Ship Mode: string, Customer ID: string, Customer Name: string, Segment: string, City: string, State: string, Country: string, Region: string, Product ID: string, Category: string, Sub-Category: string, Product Name: string, Sales: double, Quantity: int, Discount: float, Profit: double]

In [0]:
 data.show(5)

+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID| Customer Name|  Segment| City|  State|       Country|Region|     Product ID|       Category|Sub-Category|        Product Name| Sales|Quantity|Discount|Profit|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|OFF-ST-10000988|Office Supplies|     Storage|Fellowes Folders,...|  79.2|       3|     0.0|  39.6|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|TEC-AC-10004144|     Technology| Accessories|SanDisk Numeric K...|388.92|       7|     0.0|   0.0|
|     3|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|OFF-LA-10001915|Office Supplies|      Labels|Avery Legal Exhib...| 35.19|       3|     0.0| 16.11|
|     4|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|OFF-ST-10004550|Office Supplies|     Storage|Fellowes Folders,...| 50.94|       2|     0.0|  13.2|
|     5|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|TEC-AC-10004068|     Technology| Accessories|Memorex Memory Ca...|307.44|       3|     0.0| 73.71|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
only showing top 5 rows

In [0]:
data.schema

# It allows me to see the schema and most importantly to manipulate it, such as df, sql query etc.

Out[28]: StructType([StructField('Row ID', StringType(), True), StructField('Order ID', StringType(), True), StructField('Order Date', StringType(), True), StructField('Ship Date', StringType(), True), StructField('Ship Mode', StringType(), True), StructField('Customer ID', StringType(), True), StructField('Customer Name', StringType(), True), StructField('Segment', StringType(), True), StructField('City', StringType(), True), StructField('State', StringType(), True), StructField('Country', StringType(), True), StructField('Region', StringType(), True), StructField('Product ID', StringType(), True), StructField('Category', StringType(), True), StructField('Sub-Category', StringType(), True), StructField('Product Name', StringType(), True), StructField('Sales', DoubleType(), True), StructField('Quantity', IntegerType(), True), StructField('Discount', DoubleType(), True), StructField('Profit', DoubleType(), True)])

In [0]:
# generic pyspark cleaning operation
# we want to drop all the rows which has a null value in any col
 #data.dropna().show()

In [0]:
data=data.drop('Segment')

# To remove a single col

In [0]:
# To remove a multiple cols

col_to_rem = ('Country', 'Region')

In [0]:
data.drop(*col_to_rem)  
# You use * with the name assign to the col you wanna delete.

Out[32]: DataFrame[Row ID: string, Order ID: string, Order Date: string, Ship Date: string, Ship Mode: string, Customer ID: string, Customer Name: string, City: string, State: string, Product ID: string, Category: string, Sub-Category: string, Product Name: string, Sales: double, Quantity: int, Discount: double, Profit: double]

In [0]:
data = spark.read.table('sample___eu_superstore_12_csv')
data.show(2)   

# To reuse the data because of the cols we remove

+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID| Customer Name|  Segment| City|  State|       Country|Region|     Product ID|       Category|Sub-Category|        Product Name| Sales|Quantity|Discount|Profit|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|OFF-ST-10000988|Office Supplies|     Storage|Fellowes Folders,...|  79.2|       3|     0.0|  39.6|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|TEC-AC-10004144|     Technology| Accessories|SanDisk Numeric K...|388.92|       7|     0.0|   0.0|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
only showing top 2 rows

In [0]:
# To get cols/ col we use the select method

# Note if we use only select with the col without ending it with .show(), it only return the col type with the content needed

In [0]:
data.select('Country')

Out[14]: DataFrame[Country: string]

In [0]:
data.select('Country').show(2)

+--------------+
|       Country|
+--------------+
|United Kingdom|
|United Kingdom|
+--------------+
only showing top 2 rows

In [0]:
# To get multiple cols and make it a dataframe

df_CSR = data.select('Country', 'State', 'Region')

In [0]:
df_CSR.show()

# you can combine the dynamic structure of getting the columns of the dataframe

+--------------+--------------------+-------+
|       Country|               State| Region|
+--------------+--------------------+-------+
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|United Kingdom|             England|  North|
|        France|Aquitaine-Limousi...|Central|
|        France|Aquitaine-Limousi...|Central|
|        France|Aquitaine-Limousi...|Central|
|        France|Aquitaine-Limousi...|Central|
|        France|Aquitaine-Limousi...|Central|
|        France|Alsace-Champagne-...|Central|
|        France|Alsace-Champagne-...|Central|
|        France|Alsace-Champagne-...|Central|
|       Germany|North Rhine-Westp...|Central|
|       Germany|North Rhine-Westp...|Central|
+--------------+--------------------+-------+
only showing top 20 rows

In [0]:
col = data.columns

In [0]:
# And then indexing the list of it

data.select(col[:5]).show(2)

+------+---------------+----------+----------+--------------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|
+------+---------------+----------+----------+--------------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|
+------+---------------+----------+----------+--------------+
only showing top 2 rows

In [0]:
# list comprehension -> generating a lsit within a loop

[every for every in col if 'Date' in every]

Out[20]: ['Order Date', 'Ship Date']

In [0]:
# Then we pass our comprehension as an argument into are select (MORE PREFERRED THAN THE REGEX)

data.select([every for every in col if 'Date' in every]).show(2)

+----------+----------+
|Order Date| Ship Date|
+----------+----------+
|07/02/2018|11/02/2018|
|07/02/2018|11/02/2018|
+----------+----------+
only showing top 2 rows

In [0]:
# We can also use Regex

# Regex is use when the col structure comes unknown either (upper or lower cases) and you will have to build a pattern to understand.

data.select('*')

Out[22]: DataFrame[Row ID: string, Order ID: string, Order Date: string, Ship Date: string, Ship Mode: string, Customer ID: string, Customer Name: string, Segment: string, City: string, State: string, Country: string, Region: string, Product ID: string, Category: string, Sub-Category: string, Product Name: string, Sales: double, Quantity: int, Discount: float, Profit: double]

In [0]:
data.select('*').show(2)

+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID| Customer Name|  Segment| City|  State|       Country|Region|     Product ID|       Category|Sub-Category|        Product Name| Sales|Quantity|Discount|Profit|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|OFF-ST-10000988|Office Supplies|     Storage|Fellowes Folders,...|  79.2|       3|     0.0|  39.6|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|TEC-AC-10004144|     Technology| Accessories|SanDisk Numeric K...|388.92|       7|     0.0|   0.0|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+
only showing top 2 rows

In [0]:
# To get the unique value of a col

data.select('Country').distinct().show()

+--------------+
|       Country|
+--------------+
|        Sweden|
|       Germany|
|        France|
|       Belgium|
|       Finland|
|         Italy|
|        Norway|
|         Spain|
|       Denmark|
|       Ireland|
|   Switzerland|
|      Portugal|
|       Austria|
|United Kingdom|
|   Netherlands|
+--------------+

In [0]:
unique_Countries = data.select('Country').distinct()

# You do not add .show() if you wanna assign to a variable, cause it returns empty

In [0]:
unique_Countries.show()

+--------------+
|       Country|
+--------------+
|        Sweden|
|       Germany|
|        France|
|       Belgium|
|       Finland|
|         Italy|
|        Norway|
|         Spain|
|       Denmark|
|       Ireland|
|   Switzerland|
|      Portugal|
|       Austria|
|United Kingdom|
|   Netherlands|
+--------------+

In [0]:
# We do not use len in spark we use .count
unique_Countries.count()

Out[27]: 15

In [0]:
# This count all the segment

data.select('Segment').count()

Out[28]: 10000

In [0]:
# this count the distinct /unique category of segment

data.select('Segment').distinct().count()

Out[29]: 3

In [0]:
# how we can apply filtering condition on spark df

In [0]:
data.filter(data['Country'] ==  'Portugal').show(2)

+------+---------------+----------+----------+--------------+-----------+----------------+---------+------+------+--------+------+---------------+---------------+------------+--------------------+-------+--------+--------+--------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID|   Customer Name|  Segment|  City| State| Country|Region|     Product ID|       Category|Sub-Category|        Product Name|  Sales|Quantity|Discount|  Profit|
+------+---------------+----------+----------+--------------+-----------+----------------+---------+------+------+--------+------+---------------+---------------+------------+--------------------+-------+--------+--------+--------+
|   164|IT-2017-3695467|10/06/2017|14/06/2017|Standard Class|   SS-20140|Saphhira Shifley|Corporate|Lisbon|Lisboa|Portugal| South|OFF-AP-10001623|Office Supplies|  Appliances| Hoover Stove, White|3399.66|      12|     0.5|-3059.82|
|   346|IT-2018-5630655|27/08/2018|03/09/2018|Standard Class|   ZC-21910|Zuschuss Carroll| Consumer|Lisbon|Lisboa|Portugal| South|OFF-PA-10001971|Office Supplies|       Paper|Eaton Memo Slips,...|  34.35|       5|     0.5|   -11.1|
+------+---------------+----------+----------+--------------+-----------+----------------+---------+------+------+--------+------+---------------+---------------+------------+--------------------+-------+--------+--------+--------+
only showing top 2 rows

In [0]:
data.filter(data['Country'] ==  'Portugal').count()

Out[32]: 70

In [0]:
# simple filtering cond

data['Country'].isin(['Portugal', 'Spain'])

Out[33]: Column<'(Country IN (Portugal, Spain))'>

In [0]:
iberia_df = data.filter(data['Country'].isin(['Portugal', 'Spain']))  

#  iberia (the extreme southwest of Europe, which consist of Portugal & Spain)

In [0]:
iberia_df.count()

Out[35]: 929

In [0]:
# The use of and -> & and or ->| condition

In [0]:
data.filter((data['Country']  == 'Portugal') & (data['Country'] == 'Spain')).count()

# The both country must have parenthesis, & result to zero

Out[37]: 0

In [0]:
data.filter((data['Country']  == 'Portugal') | (data['Country'] == 'Spain')).count()


# Using | to filter condition result to what we needed.
# This gave us same result as cmd 47, but we can only apply .isin() to a single column, but we can apply this | condition to multiply cols

Out[38]: 929

In [0]:
data.filter((data['Segment']  == 'Corporate') & (data['Country'] == 'Spain')).count()

# You can see the conditional logical operator to filter multiple cols unlike .isin()

Out[39]: 269

In [0]:
data.filter(data['Profit'] > 0).count()

Out[40]: 7724

In [0]:
# withColumn method generate a  new col, then you can assign it to the dataframe.

data = data.withColumn('Cost', data['Sales'] - data['Profit'])

In [0]:
data.show(2)

+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID| Customer Name|  Segment| City|  State|       Country|Region|     Product ID|       Category|Sub-Category|        Product Name| Sales|Quantity|Discount|Profit|  Cost|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|OFF-ST-10000988|Office Supplies|     Storage|Fellowes Folders,...|  79.2|       3|     0.0|  39.6|  39.6|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|Aaron Smayling|Corporate|Leeds|England|United Kingdom| North|TEC-AC-10004144|     Technology| Accessories|SanDisk Numeric K...|388.92|       7|     0.0|   0.0|388.92|
+------+---------------+----------+----------+--------------+-----------+--------------+---------+-----+-------+--------------+------+---------------+---------------+------------+--------------------+------+--------+--------+------+------+
only showing top 2 rows

In [0]:
data.select('Sales', 'Profit', 'Cost').show(2)

+------+------+------+
| Sales|Profit|  Cost|
+------+------+------+
|  79.2|  39.6|  39.6|
|388.92|   0.0|388.92|
+------+------+------+
only showing top 2 rows

In [0]:
# bring everything together, wanna create a new col with conditional statement

from pyspark.sql.functions import when

In [0]:
data = data.withColumn('Profitable_flag', 
    when(data['Profit'] >= 0, 'Profitable').
    when(data['Profit'] < 0, 'Non Profitable').
    when(data['Profit'] == 0, 'Zero').
    otherwise('Error'))

In [0]:
data.select('Profit', 'Profitable_flag').show()

+-------+---------------+
| Profit|Profitable_flag|
+-------+---------------+
|   39.6|     Profitable|
|    0.0|     Profitable|
|  16.11|     Profitable|
|   13.2|     Profitable|
|  73.71|     Profitable|
|  37.92|     Profitable|
|  20.61|     Profitable|
| 192.69|     Profitable|
|1989.54|     Profitable|
|   12.6|     Profitable|
|   0.48|     Profitable|
|760.305|     Profitable|
|    0.0|     Profitable|
|790.416|     Profitable|
|-12.345| Non Profitable|
|  4.275|     Profitable|
|    0.0|     Profitable|
|   1.14|     Profitable|
|  76.44|     Profitable|
| 12.705|     Profitable|
+-------+---------------+
only showing top 20 rows

In [0]:
# We want to analyse and figure out the driver of profit.

data.columns

Out[47]: ['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'City',
 'State',
 'Country',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Cost',
 'Profitable_flag']

In [0]:
 data.select('Discount').show()

+--------+
|Discount|
+--------+
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.0|
|     0.1|
|     0.0|
|    0.15|
|     0.1|
|     0.1|
|     0.0|
|     0.0|
|     0.0|
|     0.1|
+--------+
only showing top 20 rows

In [0]:
# In how many rows where there zero discount

Zero_discount = data.filter(data['Discount'] == 0.0)

In [0]:
Zero_discount.count()

Out[50]: 6134

In [0]:
# Does discount have an impact on Profit

data.filter((data['Discount'] == 0.0) & (data['Profit'] >= 0)).count()   # 6134 profit, without discount

Out[51]: 6134

In [0]:
data.filter((data['Discount'] > 0.0) & (data['Profit'] >= 0)).count()   # 1748 profit, with discount

Out[52]: 1748

In [0]:
loss_with_discount = data.filter((data['Discount'] != 0.0) & (data['Profit'] < 0)).count()   # 2118 loss, with discount

In [0]:
data.filter((data['Discount'] <= 0.0) & (data['Profit'] == 0)).count()  # 145 No discount, No profit

Out[54]: 145

In [0]:
total_discount = data.filter(data['Discount'] != 0.0).count()   #3866
total_discount

Out[55]: 3866

In [0]:
# The sales with discount was 54% not profitable compare to the sale with profit

loss_with_discount / total_discount

Out[56]: 0.5478530781169167

In [0]:
# groupBy and Agg
# We need to state the col and the agg function

In [0]:
data.groupBy('Country').sum().show(3)

+-------+-----------------+-------------+------------------+-------------------+-----------------+
|Country|       sum(Sales)|sum(Quantity)|     sum(Discount)|        sum(Profit)|        sum(Cost)|
+-------+-----------------+-------------+------------------+-------------------+-----------------+
| Sweden|        30491.403|          753|103.10000026226044|-17519.366999999987|48010.76999999999|
|Germany|628840.0305000001|         7745|117.80000131577253| 107322.82049999991|521517.2099999996|
| France| 858931.082999999|        10804|204.35000367462635| 109029.00299999975|749902.0800000001|
+-------+-----------------+-------------+------------------+-------------------+-----------------+
only showing top 3 rows

In [0]:
data.groupBy('Country').count().show(3)

+-------+-----+
|Country|count|
+-------+-----+
| Sweden|  203|
|Germany| 2065|
| France| 2827|
+-------+-----+
only showing top 3 rows

In [0]:
# To use the groupBy and order into ascending or not
# NOTE -> You can orderby the groupby col or the agg itself.

data.groupBy('Country').sum().orderBy('Country', ascending =  False).show(3)

+--------------+------------------+-------------+------------------+-------------------+------------------+
|       Country|        sum(Sales)|sum(Quantity)|     sum(Discount)|        sum(Profit)|         sum(Cost)|
+--------------+------------------+-------------+------------------+-------------------+------------------+
|United Kingdom| 528576.2999999992|         6161|107.30000109225512| 111900.15000000001| 416676.1500000004|
|   Switzerland|24877.860000000004|          308|               0.0|  7237.470000000001|17640.389999999996|
|        Sweden|         30491.403|          753|103.10000026226044|-17519.366999999987| 48010.76999999999|
+--------------+------------------+-------------+------------------+-------------------+------------------+
only showing top 3 rows

In [0]:
data.groupBy('Country').count().orderBy('count', ascending =  False).show(3)

+--------------+-----+
|       Country|count|
+--------------+-----+
|        France| 2827|
|       Germany| 2065|
|United Kingdom| 1633|
+--------------+-----+
only showing top 3 rows

In [0]:
data.groupBy('Country', 'Segment', 'Category').count().show(3)

+--------+-----------+----------+-----+
| Country|    Segment|  Category|count|
+--------+-----------+----------+-----+
|Portugal|   Consumer| Furniture|    6|
| Belgium|Home Office|Technology|    3|
| Belgium|Home Office| Furniture|    3|
+--------+-----------+----------+-----+
only showing top 3 rows

In [0]:
data.select('Category', 'Segment').distinct().show(2)

+---------------+---------+
|       Category|  Segment|
+---------------+---------+
|     Technology|Corporate|
|Office Supplies|Corporate|
+---------------+---------+
only showing top 2 rows

In [0]:
# Using agg function

data.groupBy('Country').sum('Sales', 'Profit').show()

+--------------+------------------+-------------------+
|       Country|        sum(Sales)|        sum(Profit)|
+--------------+------------------+-------------------+
|        Sweden|         30491.403|-17519.366999999987|
|       Germany| 628840.0305000001| 107322.82049999991|
|        France|  858931.082999999| 109029.00299999975|
|       Belgium| 49226.70000000003|           11572.59|
|       Finland|20704.350000000002|            3905.73|
|         Italy|289709.65799999936| 19828.757999999965|
|        Norway|20525.370000000003|            5167.77|
|         Spain| 287146.6800000002|  54390.11999999999|
|       Denmark| 8638.053000000002|-4282.0470000000005|
|       Ireland|16639.508999999995| -7392.381000000003|
|   Switzerland|24877.860000000004|  7237.470000000001|
|      Portugal|          15105.12| -8703.059999999998|
|       Austria| 81162.00000000006|           21442.26|
|United Kingdom| 528576.2999999992| 111900.15000000001|
|   Netherlands| 77514.94500000008| -41070.07499999996|
+--------------+------------------+-------------------+

In [0]:
data.groupBy('Country').agg({'Sales': 'sum'}).show()

+--------------+------------------+
|       Country|        sum(Sales)|
+--------------+------------------+
|        Sweden|         30491.403|
|       Germany| 628840.0305000001|
|        France|  858931.082999999|
|       Belgium| 49226.70000000003|
|       Finland|20704.350000000002|
|         Italy|289709.65799999936|
|        Norway|20525.370000000003|
|         Spain| 287146.6800000002|
|       Denmark| 8638.053000000002|
|       Ireland|16639.508999999995|
|   Switzerland|24877.860000000004|
|      Portugal|          15105.12|
|       Austria| 81162.00000000006|
|United Kingdom| 528576.2999999992|
|   Netherlands| 77514.94500000008|
+--------------+------------------+

In [0]:
# We can rename the agg col and also round up large decimals

In [0]:
data.groupBy('Country').agg({'Sales':'mean'}).withColumnRenamed('avg(Sales)', 'Sales')

Out[67]: DataFrame[Country: string, Sales: double]

In [0]:
data.groupBy('Country').agg({'Sales':'mean'}).withColumnRenamed('avg(Sales)', 'Sales').show(3)

+-------+------------------+
|Country|             Sales|
+-------+------------------+
| Sweden|150.20395566502464|
|Germany| 304.5230171912834|
| France|303.83129925716275|
+-------+------------------+
only showing top 3 rows

In [0]:
# To round up this large numbers, we need to assign, we do not need to .withColumnRenamed again only if we not rounding

import pyspark.sql.functions as func

In [0]:
grouped_country = data.groupBy('Country').agg({'Sales':'mean'})

In [0]:
grouped_country = grouped_country.withColumn('Sales_clean', func.round(grouped_country['avg(Sales)'],2))

In [0]:
grouped_country.show()

+--------------+------------------+-----------+
|       Country|        avg(Sales)|Sales_clean|
+--------------+------------------+-----------+
|        Sweden|150.20395566502464|      150.2|
|       Germany| 304.5230171912834|     304.52|
|        France|303.83129925716275|     303.83|
|       Belgium| 334.8755102040819|     334.88|
|       Finland|323.50546875000003|     323.51|
|         Italy| 261.4708104693135|     261.47|
|        Norway|293.21957142857144|     293.22|
|         Spain| 334.2801862630969|     334.28|
|       Denmark| 132.8931230769231|     132.89|
|       Ireland|156.97649999999996|     156.98|
|   Switzerland|318.94692307692316|     318.95|
|      Portugal| 215.7874285714286|     215.79|
|       Austria| 300.6000000000002|      300.6|
|United Kingdom|323.68420085731736|     323.68|
|   Netherlands|178.19527586206914|      178.2|
+--------------+------------------+-----------+

In [0]:
data.groupBy('Country', 'Segment', 'Category').agg({'Sales': 'sum', 'Profit': 'sum', 'Discount': 'mean'})

Out[73]: DataFrame[Country: string, Segment: string, Category: string, sum(Sales): double, avg(Discount): double, sum(Profit): double]

In [0]:
grouped = data.groupBy('Country', 'Segment', 'Category').agg({'Sales': 'sum', 'Profit': 'sum', 'Discount': 'mean'})

In [0]:
grouped.show()

+--------------+-----------+---------------+------------------+--------------------+------------------+
|       Country|    Segment|       Category|        sum(Sales)|       avg(Discount)|       sum(Profit)|
+--------------+-----------+---------------+------------------+--------------------+------------------+
|      Portugal|   Consumer|      Furniture|          1281.675|                 0.5|-295.4249999999999|
|       Belgium|Home Office|     Technology|            2370.3|                 0.0|           1003.02|
|       Belgium|Home Office|      Furniture|1000.7400000000001|                 0.0|            327.45|
|        France|   Consumer|     Technology|152364.03899999993| 0.14039855439593826|12791.589000000009|
|        Norway|   Consumer|     Technology|3180.0899999999997|                 0.0|            432.75|
|       Finland|  Corporate|Office Supplies|           1120.35|                 0.0|            278.79|
|       Finland|   Consumer|     Technology| 4468.679999999999|                 0.0| 957.5699999999999|
|       Germany|   Consumer|Office Supplies|118187.81099999989| 0.05364511756449323|23707.191000000006|
|United Kingdom|  Corporate|     Technology|         68470.077|0.017142857398305622|17156.067000000003|
|       Ireland|Home Office|     Technology|           1906.53|                 0.5|          -1205.88|
|         Spain|   Consumer|     Technology| 52602.33900000002|  0.0505882360479411| 9772.598999999995|
|       Germany|Home Office|      Furniture| 35528.42100000001| 0.11171875102445483|          2076.381|
|       Finland|   Consumer|Office Supplies|           4817.07|                 0.0|            903.12|
|         Spain|  Corporate|      Furniture|20741.388000000003|0.048888890279663935| 316.8779999999997|
|      Portugal|   Consumer|Office Supplies|          2679.165|                 0.5|         -1345.305|
|         Italy|  Corporate|Office Supplies| 42710.18399999997| 0.07773279468057609| 8124.594000000001|
|       Finland|   Consumer|      Furniture|5987.7300000000005|                 0.0|            616.02|
|United Kingdom|Home Office|Office Supplies|32845.829999999994|0.055000000298023224|7443.1200000000035|
|       Austria|Home Office|Office Supplies| 6751.919999999998|                 0.0|1683.4499999999998|
|       Austria|   Consumer|Office Supplies|17451.629999999994|                 0.0| 4173.630000000001|
+--------------+-----------+---------------+------------------+--------------------+------------------+
only showing top 20 rows

In [0]:
# Rename the agg cols

grouped = grouped.withColumnRenamed('sum(Sales)', 'Sales').withColumnRenamed('sum(Profit)', 'Profit').withColumnRenamed('avg(Discount)', 'Discount')

In [0]:
grouped.show()

+--------------+-----------+---------------+------------------+--------------------+------------------+
|       Country|    Segment|       Category|             Sales|            Discount|            Profit|
+--------------+-----------+---------------+------------------+--------------------+------------------+
|      Portugal|   Consumer|      Furniture|          1281.675|                 0.5|-295.4249999999999|
|       Belgium|Home Office|     Technology|            2370.3|                 0.0|           1003.02|
|       Belgium|Home Office|      Furniture|1000.7400000000001|                 0.0|            327.45|
|        France|   Consumer|     Technology|152364.03899999993|  0.1403985507246372|12791.589000000009|
|        Norway|   Consumer|     Technology|3180.0899999999997|                 0.0|            432.75|
|       Finland|  Corporate|Office Supplies|           1120.35|                 0.0|            278.79|
|       Finland|   Consumer|     Technology| 4468.679999999999|                 0.0| 957.5699999999999|
|       Germany|   Consumer|Office Supplies|118187.81099999989| 0.05364511691884475|23707.191000000006|
|United Kingdom|  Corporate|     Technology|         68470.077|0.017142857142857147|17156.067000000003|
|       Ireland|Home Office|     Technology|           1906.53|                 0.5|          -1205.88|
|         Spain|   Consumer|     Technology| 52602.33900000002|0.050588235294117656| 9772.598999999995|
|       Germany|Home Office|      Furniture| 35528.42100000001| 0.11171874999999996|          2076.381|
|       Finland|   Consumer|Office Supplies|           4817.07|                 0.0|            903.12|
|         Spain|  Corporate|      Furniture|20741.388000000003|0.048888888888888885| 316.8779999999997|
|      Portugal|   Consumer|Office Supplies|          2679.165|                 0.5|         -1345.305|
|         Italy|  Corporate|Office Supplies| 42710.18399999997| 0.07773279352226718| 8124.594000000001|
|       Finland|   Consumer|      Furniture|5987.7300000000005|                 0.0|            616.02|
|United Kingdom|Home Office|Office Supplies|32845.829999999994| 0.05499999999999996|7443.1200000000035|
|       Austria|Home Office|Office Supplies| 6751.919999999998|                 0.0|1683.4499999999998|
|       Austria|   Consumer|Office Supplies|17451.629999999994|                 0.0| 4173.630000000001|
+--------------+-----------+---------------+------------------+--------------------+------------------+
only showing top 20 rows

In [0]:
grouped_country = data.groupBy('Country').agg({'Sales': 'sum'}).orderBy('sum(Sales)')
grouped_country.show()

+--------------+------------------+
|       Country|        sum(Sales)|
+--------------+------------------+
|       Denmark| 8638.053000000002|
|      Portugal|          15105.12|
|       Ireland|16639.508999999995|
|        Norway|20525.370000000003|
|       Finland|20704.350000000002|
|   Switzerland|24877.860000000004|
|        Sweden|         30491.403|
|       Belgium| 49226.70000000003|
|   Netherlands| 77514.94500000008|
|       Austria| 81162.00000000006|
|         Spain| 287146.6800000002|
|         Italy|289709.65799999936|
|United Kingdom| 528576.2999999992|
|       Germany| 628840.0305000001|
|        France|  858931.082999999|
+--------------+------------------+

In [0]:
# collect returns -> all rows from all different executors into the memory and it returns them in a list form so we can iterate.
#Note: You can only use the .collect() function when the data is completely grouped into shorter form because it will take so long if not.

grouped_country.collect()  #[:3]

Out[86]: [Row(Country='Denmark', sum(Sales)=8638.053000000002),
 Row(Country='Portugal', sum(Sales)=15105.12),
 Row(Country='Ireland', sum(Sales)=16639.508999999995),
 Row(Country='Norway', sum(Sales)=20525.370000000003),
 Row(Country='Finland', sum(Sales)=20704.350000000002),
 Row(Country='Switzerland', sum(Sales)=24877.860000000004),
 Row(Country='Sweden', sum(Sales)=30491.403),
 Row(Country='Belgium', sum(Sales)=49226.70000000003),
 Row(Country='Netherlands', sum(Sales)=77514.94500000008),
 Row(Country='Austria', sum(Sales)=81162.00000000006),
 Row(Country='Spain', sum(Sales)=287146.6800000002),
 Row(Country='Italy', sum(Sales)=289709.65799999936),
 Row(Country='United Kingdom', sum(Sales)=528576.2999999992),
 Row(Country='Germany', sum(Sales)=628840.0305000001),
 Row(Country='France', sum(Sales)=858931.082999999)]

In [0]:
bottom_country_sales = grouped_country.collect()[0][0]
bottom_country_sales

Out[80]: 'Denmark'

In [0]:
# show me all the row of the country which has the lowest sales

In [0]:
data.filter(data['Country'] == bottom_country_sales).show()

+------+---------------+----------+----------+--------------+-----------+----------------+---------+-------------+-------------+-------+------+---------------+---------------+------------+--------------------+------+--------+--------+-------+------------------+---------------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID|   Customer Name|  Segment|         City|        State|Country|Region|     Product ID|       Category|Sub-Category|        Product Name| Sales|Quantity|Discount| Profit|              Cost|Profitable_flag|
+------+---------------+----------+----------+--------------+-----------+----------------+---------+-------------+-------------+-------+------+---------------+---------------+------------+--------------------+------+--------+--------+-------+------------------+---------------+
|   626|ES-2015-4825230|18/01/2015|23/01/2015|  Second Class|   RB-19435| Richard Bierner| Consumer|      Esbjerg|South Denmark|Denmark| North|OFF-BI-10004446|Office Supplies|     Binders|Acco Binding Mach...|25.545|       1|     0.5|-10.755|36.300000000000004| Non Profitable|
|   728|ES-2017-2219250|24/09/2017|29/09/2017|Standard Class|   AR-10405|Allen Rosenblatt|Corporate|       Odense|South Denmark|Denmark| North|TEC-PH-10004825|     Technology|      Phones| Cisco Headset, VoIP| 88.53|       2|     0.5| -81.45|169.98000000000002| Non Profitable|
|   729|ES-2017-2219250|24/09/2017|29/09/2017|Standard Class|   AR-10405|Allen Rosenblatt|Corporate|       Odense|South Denmark|Denmark| North|OFF-EN-10003748|Office Supplies|   Envelopes|Ames Mailers, wit...|59.085|       3|     0.5| -1.215|60.300000000000004| Non Profitable|
|   730|ES-2017-2219250|24/09/2017|29/09/2017|Standard Class|   AR-10405|Allen Rosenblatt|Corporate|       Odense|South Denmark|Denmark| North|TEC-CO-10000070|     Technology|     Copiers|Hewlett Copy Mach...|263.67|       2|     0.5|-131.85|            395.52| Non Profitable|
|   731|ES-2017-2219250|24/09/2017|29/09/2017|Standard Class|   AR-10405|Allen Rosenblatt|Corporate|       Odense|South Denmark|Denmark| North|TEC-PH-10004635|     Technology|      Phones|Samsung Office Te...|195.66|       6|     0.5|-105.66|            301.32| Non Profitable|
|   732|ES-2017-2219250|24/09/2017|29/09/2017|Standard Class|   AR-10405|Allen Rosenblatt|Corporate|       Odense|South Denmark|Denmark| North|TEC-PH-10003963|     Technology|      Phones|Apple Signal Boos...| 68.97|       1|     0.5|  -62.1|            131.07| Non Profitable|
|   733|ES-2017-2219250|24/09/2017|29/09/2017|Standard Class|   AR-10405|Allen Rosenblatt|Corporate|       Odense|South Denmark|Denmark| North|OFF-EN-10002240|Office Supplies|   Envelopes|GlobeWeis Clasp E...| 20.16|       3|     0.5|  -5.31|             25.47| Non Profitable|
|  1068|ES-2015-4508489|15/09/2015|20/09/2015|Standard Class|   BP-11155|       Becky Pak| Consumer|      Esbjerg|South Denmark|Denmark| North|OFF-ST-10001648|Office Supplies|     Storage|Tenex Shelving, Blue| 81.99|       3|     0.5|  -73.8|            155.79| Non Profitable|
|  1069|ES-2015-4508489|15/09/2015|20/09/2015|Standard Class|   BP-11155|       Becky Pak| Consumer|      Esbjerg|South Denmark|Denmark| North|OFF-AR-10004884|Office Supplies|         Art|Sanford Pens, Flu...| 24.72|       4|     0.5| -10.92|             35.64| Non Profitable|
|  1466|ES-2018-5200052|23/10/2018|28/10/2018|Standard Class|   JD-16060|    Julia Dunbar| Consumer|      Esbjerg|South Denmark|Denmark| North|OFF-SU-10000782|Office Supplies|    Supplies|Fiskars Shears, S...| 88.68|       4|     0.5| -37.32|             126.0| Non Profitable|
|  1501|IT-2017-4649004|31/05/2017|06/06/2017|Standard Class|   BF-11080|       Bart Folk| Consumer|   Copenhagen|  Hovedstaden|Denmark| North|TEC-AC-10000254|     Technology| Accessories|Belkin Keyboard, ...|298.83|       7|     0.5| -197.4|            496.23| Non Profitable|
|  1502|IT-2017-4649004|31/05/2017|06/06/2017|Standard Class|   BF-11080|       Bart Folk| Consumer|   Copenhagen|  Hovedstaden|Denmark| North|OFF-ST-10003335|Office Supplies|     Storage|     Smead Box, Blue|16.155|       3|     0.5|-16.155|             32.31| Non Profitable|
|  1503|IT-2017-4649004|31/05/2017|06/06/2017|Standard Class|   BF-11080|       Bart Folk| Consumer|   Copenhagen|  Hovedstaden|Denmark| North|OFF-EN-10003630|Office Supplies|   Envelopes|GlobeWeis Busines...| 26.01|       3|     0.5| -11.97|37.980000000000004| Non Profitable|
|  1504|IT-2017-4649004|31/05/2017|06/06/2017|Standard Class|   BF-11080|       Bart Folk| Consumer|   Copenhagen|  Hovedstaden|Denmark| North|FUR-CH-10004774|      Furniture|      Chairs|Novimex Executive...| 920.4|       4|     0.5|-276.12|           1196.52| Non Profitable|
|  1993|ES-2017-4250046|16/08/2017|20/08/2017|  Second Class|   CS-11950|  Carlos Soltero| Consumer|Frederiksberg|  Hovedstaden|Denmark| North|OFF-BI-10002225|Office Supplies|     Binders|Cardinal Binding ...| 51.27|       2|     0.5| -15.39|             66.66| Non Profitable|
|  1994|ES-2017-4250046|16/08/2017|20/08/2017|  Second Class|   CS-11950|  Carlos Soltero| Consumer|Frederiksberg|  Hovedstaden|Denmark| North|OFF-AR-10003247|Office Supplies|         Art|Boston Highlighte...|  44.1|       4|     0.5| -28.26|             72.36| Non Profitable|
|  1995|ES-2017-4250046|16/08/2017|20/08/2017|  Second Class|   CS-11950|  Carlos Soltero| Consumer|Frederiksberg|  Hovedstaden|Denmark| North|OFF-PA-10002040|Office Supplies|       Paper|Green Bar Cards &...|  49.8|       2|     0.5| -37.86|             87.66| Non Profitable|
|  1996|ES-2017-4250046|16/08/2017|20/08/2017|  Second Class|   CS-11950|  Carlos Soltero| Consumer|Frederiksberg|  Hovedstaden|Denmark| North|OFF-AP-10002413|Office Supplies|  Appliances|Breville Coffee G...|91.935|       3|     0.5|-27.585|119.52000000000001| Non Profitable|
|  1997|ES-2017-4250046|16/08/2017|20/08/2017|  Second Class|   CS-11950|  Carlos Soltero| Consumer|Frederiksberg|  Hovedstaden|Denmark| North|OFF-AR-10000594|Office Supplies|         Art|Binney & Smith Hi...| 19.77|       2|     0.5|  -3.21|             22.98| Non Profitable|
|  2583|ES-2018-1415600|07/07/2018|12/07/2018|Standard Class|   DK-12835| Damala Kotsonis|Corporate|   Sonderborg|South Denmark|Denmark| North|OFF-FA-10001330|Office Supplies|   Fasteners|OIC Rubber Bands,...| 17.07|       2|     0.5|  -3.09|             20.16| Non Profitable|
+------+---------------+----------+----------+--------------+-----------+----------------+---------+-------------+-------------+-------+------+---------------+---------------+------------+--------------------+------+--------+--------+-------+------------------+---------------+
only showing top 20 rows

In [0]:
# show me all the row of the bottom 3 countries which has the lowest profit

In [0]:
bottom3_country_profit = data.groupBy('Country').agg({'Profit': 'sum'}).orderBy('sum(Profit)').collect()[:3]
bottom3_country_profit

Out[219]: [Row(Country='Netherlands', sum(Profit)=-41070.07499999996),
 Row(Country='Sweden', sum(Profit)=-17519.366999999987),
 Row(Country='Portugal', sum(Profit)=-8703.059999999998)]

In [0]:
# iterate through to get the all the rows of the country using a list comprehension

bottom_countries = [every[0] for every in bottom3_country_profit]
bottom_countries

Out[220]: ['Netherlands', 'Sweden', 'Portugal']

In [0]:
data.filter(data['Country'].isin(bottom_countries)).show()

+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-----------+-------------+-----------+-------+---------------+---------------+------------+--------------------+-------+--------+--------+--------+------------------+---------------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID|   Customer Name|    Segment|       City|        State|    Country| Region|     Product ID|       Category|Sub-Category|        Product Name|  Sales|Quantity|Discount|  Profit|              Cost|Profitable_flag|
+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-----------+-------------+-----------+-------+---------------+---------------+------------+--------------------+-------+--------+--------+--------+------------------+---------------+
|    41|IT-2017-2373016|08/11/2017|11/11/2017|   First Class|   CM-11830|  Cari MacIntyre|  Corporate|  The Hague|South Holland|Netherlands|Central|OFF-SU-10003907|Office Supplies|    Supplies|Stiletto Letter O...|   15.0|       1|     0.5|    -9.3|              24.3| Non Profitable|
|    42|IT-2017-2373016|08/11/2017|11/11/2017|   First Class|   CM-11830|  Cari MacIntyre|  Corporate|  The Hague|South Holland|Netherlands|Central|OFF-BI-10001249|Office Supplies|     Binders|Acco Hole Reinfor...|  14.04|       4|     0.5|     0.0|             14.04|     Profitable|
|    43|IT-2017-2373016|08/11/2017|11/11/2017|   First Class|   CM-11830|  Cari MacIntyre|  Corporate|  The Hague|South Holland|Netherlands|Central|OFF-AR-10000823|Office Supplies|         Art|Stanley Pens, Wat...| 33.075|       5|     0.5| -11.925|              45.0| Non Profitable|
|    51|IT-2018-2321796|02/04/2018|07/04/2018|Standard Class|   IL-15100|     Ivan Liston|   Consumer|      Nacka|    Stockholm|     Sweden|  North|OFF-ST-10002659|Office Supplies|     Storage|Smead Shelving, W...|   72.0|       3|     0.5|   -5.76|             77.76| Non Profitable|
|   105|IT-2017-4388990|10/08/2017|13/08/2017|  Second Class|   MM-17260| Magdelene Morse|   Consumer|Vlaardingen|South Holland|Netherlands|Central|FUR-FU-10004137|      Furniture| Furnishings|Tenex Light Bulb,...|  84.24|       6|     0.2|  -15.84|            100.08| Non Profitable|
|   106|IT-2017-4388990|10/08/2017|13/08/2017|  Second Class|   MM-17260| Magdelene Morse|   Consumer|Vlaardingen|South Holland|Netherlands|Central|OFF-ST-10001413|Office Supplies|     Storage|Rogers Folders, Blue|  30.69|       2|     0.5|  -29.49|             60.18| Non Profitable|
|   143|IT-2015-5134922|16/10/2015|18/10/2015|  Second Class|   BS-11365|    Bill Shonely|  Corporate|  Rotterdam|South Holland|Netherlands|Central|OFF-PA-10001662|Office Supplies|       Paper|Green Bar Note Ca...| 14.895|       1|     0.5|  -4.185|             19.08| Non Profitable|
|   144|IT-2015-5134922|16/10/2015|18/10/2015|  Second Class|   BS-11365|    Bill Shonely|  Corporate|  Rotterdam|South Holland|Netherlands|Central|OFF-ST-10002263|Office Supplies|     Storage|Rogers Trays, Wir...|151.875|       5|     0.5|  -3.075|            154.95| Non Profitable|
|   145|IT-2016-2655811|16/06/2016|22/06/2016|Standard Class|   MT-18070|   Michelle Tran|Home Office|  Rotterdam|South Holland|Netherlands|Central|TEC-AC-10002530|     Technology| Accessories|Memorex Numeric K...|  86.04|       4|     0.5|  -29.28|115.32000000000001| Non Profitable|
|   146|IT-2016-2655811|16/06/2016|22/06/2016|Standard Class|   MT-18070|   Michelle Tran|Home Office|  Rotterdam|South Holland|Netherlands|Central|OFF-AR-10001672|Office Supplies|         Art|Boston Sketch Pad...|  48.87|       2|     0.5|  -20.55|             69.42| Non Profitable|
|   164|IT-2017-3695467|10/06/2017|14/06/2017|Standard Class|   SS-20140|Saphhira Shifley|  Corporate|     Lisbon|       Lisboa|   Portugal|  South|OFF-AP-10001623|Office Supplies|  Appliances| Hoover Stove, White|3399.66|      12|     0.5|-3059.82|           6459.48| Non Profitable|
|   181|IT-2018-5192801|25/12/2018|01/01/2019|Standard Class|   JD-15895|Jonathan Doherty|  Corporate| Oosterhout|North Brabant|Netherlands|Central|OFF-LA-10003699|Office Supplies|      Labels|Smead File Folder...|  23.73|       7|     0.5|   -21.0|44.730000000000004| Non Profitable|
|   191|IT-2016-4187289|10/05/2016|12/05/2016|  Second Class|   LC-16960| Lindsay Castell|Home Office|  Amsterdam|North Holland|Netherlands|Central|OFF-FA-10000740|Office Supplies|   Fasteners|Accos Staples, Bu...|  10.95|       2|     0.5|   -6.57|             17.52| Non Profitable|
|   296|IT-2015-5989878|20/10/2015|24/10/2015|Standard Class|   RS-19870|      Roy Skaria|Home Office|    Helmond|North Brabant|Netherlands|Central|OFF-AR-10003457|Office Supplies|         Art|Sanford Sketch Pa...|  72.99|       3|     0.5|   -4.41| 77.39999999999999| Non Profitable|
|   340|IT-2016-1188964|10/06/2016|17/06/2016|Standard Class|   JK-16090|   Juliana Krohn|   Consumer|    Uppsala|      Uppsala|     Sweden|  North|FUR-CH-10004790|      Furniture|      Chairs|Office Star Bag C...| 159.03|       6|     0.5|  -28.71|            187.74| Non Profitable|
|   341|IT-2016-1188964|10/06/2016|17/06/2016|Standard Class|   JK-16090|   Juliana Krohn|   Consumer|    Uppsala|      Uppsala|     Sweden|  North|OFF-PA-10001492|Office Supplies|       Paper|Enermax Note Card...|  59.82|       4|     0.5|  -34.74|             94.56| Non Profitable|
|   342|IT-2016-1188964|10/06/2016|17/06/2016|Standard Class|   JK-16090|   Juliana Krohn|   Consumer|    Uppsala|      Uppsala|     Sweden|  North|OFF-PA-10000816|Office Supplies|       Paper|Enermax Memo Slip...|  7.785|       1|     0.5|  -4.845|12.629999999999999| Non Profitable|
|   343|IT-2016-1188964|10/06/2016|17/06/2016|Standard Class|   JK-16090|   Juliana Krohn|   Consumer|    Uppsala|      Uppsala|     Sweden|  North|OFF-FA-10004359|Office Supplies|   Fasteners|OIC Paper Clips, ...|  11.88|       2|     0.5|   -5.94|             17.82| Non Profitable|
|   344|IT-2016-1188964|10/06/2016|17/06/2016|Standard Class|   JK-16090|   Juliana Krohn|   Consumer|    Uppsala|      Uppsala|     Sweden|  North|TEC-PH-10001963|     Technology|      Phones|Nokia Speaker Pho...| 248.88|       4|     0.5|  -149.4|            398.28| Non Profitable|
|   346|IT-2018-5630655|27/08/2018|03/09/2018|Standard Class|   ZC-21910|Zuschuss Carroll|   Consumer|     Lisbon|       Lisboa|   Portugal|  South|OFF-PA-10001971|Office Supplies|       Paper|Eaton Memo Slips,...|  34.35|       5|     0.5|   -11.1|             45.45| Non Profitable|
+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-----------+-------------+-----------+-------+---------------+---------------+------------+--------------------+-------+--------+--------+--------+------------------+---------------+
only showing top 20 rows

In [0]:
data.select('Order Date').orderBy('Order Date').show(5)

# it cannot be ordered because the date is not in it right format it is in a str format, so it is ordering by the 1st of each yr

+----------+
|Order Date|
+----------+
|01/01/2015|
|01/01/2016|
|01/01/2016|
|01/01/2016|
|01/01/2017|
+----------+
only showing top 5 rows

In [0]:
# How to change the format of a date in pyspark

from pyspark.sql import functions as f

In [0]:
# we want to make a new col for it as we changing the date format

data.withColumn('clean order date', f.to_date(data['Order Date'], 'dd/MM/yyyy')).select('Order Date', 'clean order date').printSchema()

root
 |-- Order Date: string (nullable = true)
 |-- clean order date: date (nullable = true)

In [0]:
# backlash \ at the end to continue in the next line helps well without given an err.

data = data.withColumn('clean order date', f.to_date(data['Order Date'], 'dd/MM/yyyy')).\
       withColumn('clean ship date', f.to_date(data['Ship Date'], 'dd/MM/yyyy'))
#data.show()

In [0]:
# You can now order the clean order date.

data.select('clean ship date', 'clean order date').orderBy('clean order date').printSchema()#show(5)

root
 |-- clean ship date: date (nullable = true)
 |-- clean order date: date (nullable = true)

In [0]:
# udf -> user Define Function 
# Note: udf is an expensive function in pyspark and it is preferrable to apply it on grouped data.

from pyspark.sql.functions import udf

# which makes you define the function you want

In [0]:
# we want to create a new col for customer name with uppercase all through

def makeupper(mystring):
    return mystring.upper()

upperUDF = udf(lambda x : makeupper(x))

# create a new col for the uppercase of the col you wanna use

data = data.withColumn('upper case name', upperUDF(data['Customer Name']))
data.show()

+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-------------+--------------------+--------------+-------+---------------+---------------+------------+--------------------+--------+--------+--------+-------+------------------+---------------+----------------+---------------+---------------+----------------+
|Row ID|       Order ID|Order Date| Ship Date|     Ship Mode|Customer ID|   Customer Name|    Segment|         City|               State|       Country| Region|     Product ID|       Category|Sub-Category|        Product Name|   Sales|Quantity|Discount| Profit|              Cost|Profitable_flag|clean order date|ship order date|clean ship date| upper case name|
+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-------------+--------------------+--------------+-------+---------------+---------------+------------+--------------------+--------+--------+--------+-------+------------------+---------------+----------------+---------------+---------------+----------------+
|     1|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-ST-10000988|Office Supplies|     Storage|Fellowes Folders,...|    79.2|       3|     0.0|   39.6|              39.6|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     2|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|TEC-AC-10004144|     Technology| Accessories|SanDisk Numeric K...|  388.92|       7|     0.0|    0.0|            388.92|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     3|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-LA-10001915|Office Supplies|      Labels|Avery Legal Exhib...|   35.19|       3|     0.0|  16.11|             19.08|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     4|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-ST-10004550|Office Supplies|     Storage|Fellowes Folders,...|   50.94|       2|     0.0|   13.2|37.739999999999995|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     5|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|TEC-AC-10004068|     Technology| Accessories|Memorex Memory Ca...|  307.44|       3|     0.0|  73.71|233.73000000000002|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     6|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|OFF-ST-10002271|Office Supplies|     Storage|Rogers Shelving, ...|   122.4|       2|     0.0|  37.92|             84.48|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     7|ES-2018-1311038|07/02/2018|11/02/2018|Standard Class|   AS-10045|  Aaron Smayling|  Corporate|        Leeds|             England|United Kingdom|  North|TEC-PH-10003963|     Technology|      Phones|Apple Signal Boos...|  413.82|       3|     0.0|  20.61|            393.21|     Profitable|      2018-02-07|     2018-02-11|     2018-02-11|  AARON SMAYLING|
|     8|ES-2016-5113958|02/08/2016|07/08/2016|  Second Class|   EB-13840|   Ellis Ballard|  Corporate|West Bromwich|             England|United Kingdom|  North|TEC-CO-10004325|     Technology|     Copiers|Canon Personal Co...|  428.22|       3|     0.0| 192.69|235.53000000000003|     Profitable|      2016-08-02|     2016-08-07|     2016-08-07|   ELLIS BALLARD|
|     9|ES-2016-5113958|02/08/2016|07/08/2016|  Second Class|   EB-13840|   Ellis Ballard|  Corporate|West Bromwich|             England|United Kingdom|  North|OFF-AP-10004512|Office Supplies|  Appliances|   Hoover Stove, Red| 3979.29|       7|     0.0|1989.54|           1989.75|     Profitable|      2016-08-02|     2016-08-07|     2016-08-07|   ELLIS BALLARD|
|    10|ES-2016-5113958|02/08/2016|07/08/2016|  Second Class|   EB-13840|   Ellis Ballard|  Corporate|West Bromwich|             England|United Kingdom|  North|OFF-FA-10002393|Office Supplies|   Fasteners|Accos Push Pins, ...|   43.56|       3|     0.0|   12.6|             30.96|     Profitable|      2016-08-02|     2016-08-07|     2016-08-07|   ELLIS BALLARD|
|    11|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-LA-10002805|Office Supplies|      Labels|Hon Color Coded L...|   25.26|       2|     0.0|   0.48|             24.78|     Profitable|      2016-06-20|     2016-06-20|     2016-06-20|LOGAN HAUSHALTER|
|    12|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-AP-10002330|Office Supplies|  Appliances|Hamilton Beach St...|2443.905|       5|     0.1|760.305|1683.6000000000004|     Profitable|      2016-06-20|     2016-06-20|     2016-06-20|LOGAN HAUSHALTER|
|    13|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-AR-10000505|Office Supplies|         Art|Binney & Smith Pe...|   12.21|       1|     0.0|    0.0|             12.21|     Profitable|      2016-06-20|     2016-06-20|     2016-06-20|LOGAN HAUSHALTER|
|    14|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|TEC-PH-10002898|     Technology|      Phones|Samsung Smart Pho...|2167.296|       4|    0.15|790.416|1376.8799999999997|     Profitable|      2016-06-20|     2016-06-20|     2016-06-20|LOGAN HAUSHALTER|
|    15|ES-2016-2510515|20/06/2016|20/06/2016|      Same Day|   LH-17155|Logan Haushalter|   Consumer|   Le Bouscat|Aquitaine-Limousi...|        France|Central|OFF-ST-10001413|Office Supplies|     Storage|Rogers Folders, Blue| 138.105|       5|     0.1|-12.345|            150.45| Non Profitable|      2016-06-20|     2016-06-20|     2016-06-20|LOGAN HAUSHALTER|
|    16|ES-2017-4380115|16/02/2017|20/02/2017|Standard Class|   KC-16540| Kelly Collister|   Consumer|   Strasbourg|Alsace-Champagne-...|        France|Central|OFF-ST-10003931|Office Supplies|     Storage|Smead Trays, Wire...| 128.385|       3|     0.1|  4.275|124.10999999999999|     Profitable|      2017-02-16|     2017-02-20|     2017-02-20| KELLY COLLISTER|
|    17|ES-2017-4380115|16/02/2017|20/02/2017|Standard Class|   KC-16540| Kelly Collister|   Consumer|   Strasbourg|Alsace-Champagne-...|        France|Central|TEC-AC-10004269|     Technology| Accessories|Belkin Memory Car...|  690.12|       6|     0.0|    0.0|            690.12|     Profitable|      2017-02-16|     2017-02-20|     2017-02-20| KELLY COLLISTER|
|    18|ES-2017-4380115|16/02/2017|20/02/2017|Standard Class|   KC-16540| Kelly Collister|   Consumer|   Strasbourg|Alsace-Champagne-...|        France|Central|OFF-LA-10001676|Office Supplies|      Labels|Hon Removable Lab...|    8.16|       1|     0.0|   1.14|7.0200000000000005|     Profitable|      2017-02-16|     2017-02-20|     2017-02-20| KELLY COLLISTER|
|    19|ES-2018-2573330|03/11/2018|08/11/2018|Standard Class|   BF-11170|      Ben Ferrer|Home Office|         Unna|North Rhine-Westp...|       Germany|Central|TEC-MA-10000811|     Technology|    Machines|Okidata Phone, Du...|  347.88|       4|     0.0|  76.44|            271.44|     Profitable|      2018-11-03|     2018-11-08|     2018-11-08|      BEN FERRER|
|    20|ES-2018-2573330|03/11/2018|08/11/2018|Standard Class|   BF-11170|      Ben Ferrer|Home Office|         Unna|North Rhine-Westp...|       Germany|Central|OFF-ST-10000648|Office Supplies|     Storage|Eldon File Cart, ...| 575.505|       5|     0.1| 12.705|             562.8|     Profitable|      2018-11-03|     2018-11-08|     2018-11-08|      BEN FERRER|
+------+---------------+----------+----------+--------------+-----------+----------------+-----------+-------------+--------------------+--------------+-------+---------------+---------------+------------+--------------------+--------+--------+--------+-------+------------------+---------------+----------------+---------------+---------------+----------------+
only showing top 20 rows

In [0]:
data.select('Customer Name', 'upper case name').show(5)

+--------------+---------------+
| Customer Name|upper case name|
+--------------+---------------+
|Aaron Smayling| AARON SMAYLING|
|Aaron Smayling| AARON SMAYLING|
|Aaron Smayling| AARON SMAYLING|
|Aaron Smayling| AARON SMAYLING|
|Aaron Smayling| AARON SMAYLING|
+--------------+---------------+
only showing top 5 rows